#!/usr/bin/env bash
# Personnel Registry installer.
#
# Safe to re-run: an existing .env is kept as it is and only missing values are
# filled in. Nothing is overwritten, so your edits and your database survive.
#
#   ./install.sh                 first install, or repair a partial one
#   ./install.sh --engine mariadb    choose the database on a first install
set -euo pipefail

# ---- defaults you can change ------------------------------------------------
DEFAULT_ENGINE="postgres"
DEFAULT_WEB_PORT="5060"       # as specified; browsers block it, see README
DEFAULT_WEB_ALT_PORT="8060"   # the port to actually open in a browser
DEFAULT_DB_PORT="5061"
DEFAULT_ADMIN_USERNAME="admin"
DEFAULT_APP_TITLE="Personnel Registry"
# -----------------------------------------------------------------------------

cd "$(dirname "$0")"
ENV_FILE=".env"
ENGINE=""
say() { printf '%s\n' "$*"; }
fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --engine) ENGINE="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

# ---- checks -----------------------------------------------------------------
command -v docker >/dev/null 2>&1 || fail "Docker isn't installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "The Docker Compose plugin isn't available. Install docker-compose-plugin."
docker info >/dev/null 2>&1 || fail "Can't talk to the Docker daemon. Start it, or add yourself to the docker group and log in again."

secret() { docker run --rm python:3.13-slim python -c "import secrets;print(secrets.token_urlsafe(${1:-32}))" 2>/dev/null \
  || python3 -c "import secrets;print(secrets.token_urlsafe(${1:-32}))" 2>/dev/null \
  || LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${2:-44}"; }

get() { [ -f "$ENV_FILE" ] && sed -n "s/^$1=//p" "$ENV_FILE" | head -n1 || true; }

port_busy() {
  if command -v ss >/dev/null 2>&1; then ss -ltn 2>/dev/null | grep -q ":$1 "
  elif command -v netstat >/dev/null 2>&1; then netstat -ltn 2>/dev/null | grep -q ":$1 "
  else return 1; fi
}

# ---- write or complete .env -------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  say "Found an existing .env. Keeping it, and filling in anything missing."
  ENGINE="$(get DB_ENGINE)"
else
  if [ -z "$ENGINE" ]; then
    if [ -t 0 ]; then
      printf 'Which database? [1] PostgreSQL (default)  [2] MariaDB : '
      read -r choice || choice=""
      case "$choice" in 2|mariadb|MariaDB) ENGINE="mariadb" ;; *) ENGINE="$DEFAULT_ENGINE" ;; esac
    else
      ENGINE="$DEFAULT_ENGINE"
    fi
  fi
  case "$ENGINE" in postgres|mariadb) ;; *) fail "--engine must be postgres or mariadb" ;; esac

  sed \
    -e "s|^DB_PASSWORD=.*|DB_PASSWORD=$(secret 32 44)|" \
    -e "s|^ADMIN_USERNAME=.*|ADMIN_USERNAME=$DEFAULT_ADMIN_USERNAME|" \
    -e "s|^APP_TITLE=.*|APP_TITLE=$DEFAULT_APP_TITLE|" \
    -e "s|^WEB_PORT=.*|WEB_PORT=$DEFAULT_WEB_PORT|" \
    -e "s|^WEB_ALT_PORT=.*|WEB_ALT_PORT=$DEFAULT_WEB_ALT_PORT|" \
    -e "s|^DB_PORT=.*|DB_PORT=$DEFAULT_DB_PORT|" \
    .env.example > "$ENV_FILE"
  printf 'DB_ENGINE=%s\n' "$ENGINE" >> "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  NEW_INSTALL=1
fi

# The session key and the first admin password are generated by the app itself
# and written to its log, so only the database password is needed here.
for key in DB_PASSWORD; do
  if [ -z "$(get "$key")" ]; then
    value="$(secret 32 44)"
    if grep -q "^$key=" "$ENV_FILE"; then
      tmp="$(mktemp)"; sed "s|^$key=.*|$key=$value|" "$ENV_FILE" > "$tmp"; cat "$tmp" > "$ENV_FILE"; rm -f "$tmp"
    else
      printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
    say "Generated a new $key."
  fi
done

WEB_PORT="$(get WEB_PORT)";  WEB_PORT="${WEB_PORT:-$DEFAULT_WEB_PORT}"
WEB_ALT_PORT="$(get WEB_ALT_PORT)"; WEB_ALT_PORT="${WEB_ALT_PORT:-$DEFAULT_WEB_ALT_PORT}"
DB_PORT="$(get DB_PORT)";    DB_PORT="${DB_PORT:-$DEFAULT_DB_PORT}"

for p in "$WEB_PORT" "$WEB_ALT_PORT" "$DB_PORT"; do
  if port_busy "$p"; then
    say "Warning: something is already listening on port $p. Change it in .env if the stack fails to start."
  fi
done

# ---- build and start --------------------------------------------------------
say ""
case "$ENGINE" in mariadb) COMPOSE_FILE="compose.mariadb.yaml" ;; *) COMPOSE_FILE="compose.yaml" ;; esac
say "Starting the stack ($ENGINE, $COMPOSE_FILE)..."
DC="docker compose -f $COMPOSE_FILE"
$DC pull || true
$DC up -d

say "Waiting for the registry to come up..."
for i in $(seq 1 60); do
  if $DC exec -T app python -c "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8080/healthz',timeout=3)" >/dev/null 2>&1; then
    READY=1; break
  fi
  sleep 2
done

if [ "${READY:-0}" != "1" ]; then
  say ""
  say "The registry hasn't answered yet. Check the logs with:  docker compose -f $COMPOSE_FILE logs -f app"
  exit 1
fi

HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"; HOST_IP="${HOST_IP:-localhost}"
say ""
say "Ready."
say ""
say "  Open   http://$HOST_IP:$WEB_ALT_PORT"
say "  Port $WEB_PORT also serves the same interface, but browsers block it by"
say "  default because $WEB_PORT is the SIP port. See the README if you need it."
say ""
if [ "${NEW_INSTALL:-0}" = "1" ]; then
  say "  The first account's password was generated and written to the app log:"
  say ""
  docker compose -f "$COMPOSE_FILE" logs app 2>/dev/null | grep -A3 "First account created" || \
    say "    docker compose -f $COMPOSE_FILE logs app | grep -A3 'First account created'"
  say ""
fi
say "  Database is on port $DB_PORT (localhost only until you change DB_BIND_ADDRESS)."
